# NumPy

NumPy is an acronym for "Numeric Python" or "Numerical Python".

NumPy is the fundamental package for scientific computing with Python. It is an open source extension module for Python.

1. A powerful N-dimensional array object
2. Sophisticated (broadcasting) functions
3. Useful linear algebra, Fourier transform, and random number capabilities
4. Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data 
5. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of database



1. Мощный объект N-мерного массива
2. Сложные (вещательные) функции
3. Полезные возможности линейной алгебры, преобразования Фурье и случайных чисел
4. Помимо очевидного научного использования, NumPy также может использоваться в качестве эффективного многомерного контейнера общих данных
5. Можно определить произвольные типы данных. Это позволяет NumPy легко и быстро интегрироваться с широким спектром баз данных

Source: numpy.org

# Notebook Contents

##### <span style="color:green">1. A simple numpy array example</span>
##### <span style="color:green">2. Functions to create an array</span>
#####  <span style="color:green">3. Dimensionality of an array</span>
##### <span style="color:green">4. The shape of an array</span>
##### <span style="color:green">5. Just for fun</span>

## A simple numpy array example

We will create two arrays SV and S_V 
- Using lists
- Using tuples 

In [2]:
# We will first import the 'numpy' module
import numpy as np

In [3]:
stock_values = [20.3, 25.3, 22.7, 19.0, 18.5,
                21.2, 24.5, 26.6, 23.2, 21.2]  # This is a list

In [4]:
# Converting a list into an array

SV = np.array(stock_values)

print(SV)

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]


In [5]:
type(SV)  # Understanding the data type of 'SV'

numpy.ndarray

In [6]:
stockvalues = (20.3, 25.3, 22.7, 19.0, 18.5, 21.2, 24.5,
               26.6, 23.2, 21.2)  # This is a tuple

# Converting tuple into an array
S_V = np.array(stockvalues)
print(S_V)

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]


In [7]:
type(S_V)  # Understanding the data type of 'S_V'

numpy.ndarray

## Functions to create arrays quickly 

The above-discussed methods to create arrays require us to manually input the data points. To automatically create data points for an array we use these functions: 
- **arange**
- **linspace**

Both these functions create data points lying between two endpoints, starting and ending, so that they are evenly distributed. For example, we can create 50 data points lying between 1 and 10. \



## Функции для быстрого создания массивов

Описанные выше методы создания массивов требуют, чтобы мы вручную вводили точки данных. Для автоматического создания точек данных для массива мы используем следующие функции:
- **арандж**
- **linspace**

Обе эти функции создают точки данных, расположенные между двумя конечными точками, начиная и заканчивая, чтобы они были равномерно распределены. Например, мы можем создать 50 точек данных, лежащих между 1 и 10.

### arange

Numpy.arange returns evenly spaced arrays by using a 'given' step or interval by the user.

Numpy.arange возвращает равномерно расположенные массивы, используя "заданный" пользователем шаг или интервал.

Syntax:
####  arange ([start], [stop], [step], [dtype=None])

The 'start and the 'stop' determines the range of the array. 'Step' determines the spacing between two adjacent values. The datatype of the output array can be determined by setting the parameter 'dtype'. 

In [9]:
# If the start parameter is not given, it will be set to 0

# '10' is the stop parameter

# The default interval for a step is '1'

# If the 'dtype' is not given, then it will be automatically inferred from the other input arguments

a = np.arange(10)  # Syntax a = np.arange (0,10,1,None)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# Here the range is '1 to 15'. It will include 1 and exclude 15

b = np.arange(1, 15)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [11]:
# We have changed the 'step' or spacing between two adjacent values, from a default 1, to a user given value of 2

c = np.arange(0, 21, 2)
print(c)

[ 0  2  4  6  8 10 12 14 16 18 20]


In [12]:
# Even though our input arguments are of the datatype 'float', it will return an 'int' array
# Since we have set the 'dtype' parameter as 'int'

d = np.arange(1.3, 23.3, 2.1, int)
print(d)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [13]:
# You may now be able to understand this example, all by yourself

e = np.arange(1.4, 23.6, 1, float)
print(e)

[ 1.4  2.4  3.4  4.4  5.4  6.4  7.4  8.4  9.4 10.4 11.4 12.4 13.4 14.4
 15.4 16.4 17.4 18.4 19.4 20.4 21.4 22.4 23.4]


### linspace

Numpy.linspace also returns an evenly spaced array but needs the 'number of array elements' as an input from the user and creates the distance automatically.

Numpy.linspace также возвращает равномерно распределенный массив, но нуждается в "количестве элементов массива" в качестве входных данных от пользователя и автоматически создает расстояние.

Syntax:
#### linspace(start, stop, num=50, endpoint=True, retstep=False)

The 'start and the 'stop' determines the range of the array. 'num' determines the number of elements in the array. If the 'endpoint' is True, it will include the stop value and if it is false, the array will exclude the stop value.

If the optional parameter 'retstep' is set, the function will return the value of the spacing between adjacent values.


__"Старт" и "стоп"__ определяют диапазон массива. "num" определяет количество элементов в массиве. Если "конечная точка" имеет значение True, она будет включать значение stop, а если значение false, массив исключит значение stop.

Если установлен необязательный параметр "retstep", функция вернет значение расстояния между соседними значениями.

In [14]:
# By default, since the 'num' is not given, it will divide the range into 50 individual array elements

# By default, it even includes the 'endpoint' of the range, since it is set to True by default

a = np.linspace(1, 10)
print(a)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [15]:
# This time around, we have specified that we want the range of 1 - 10 to be divided into 8 individual array elements

b = np.linspace(1, 10, 8)
print(b)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [16]:
# In this line, we have specified not to include the end point of the range

c = np.linspace(1, 10, 8, False)
print(c)

[1.    2.125 3.25  4.375 5.5   6.625 7.75  8.875]


In [17]:
# In this line, we have specified 'retstep' as true, the function will return the value of the spacing between adjacent values

d = np.linspace(1, 10, 8, True, True)
print(d)

(array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ]), 1.2857142857142858)


In [18]:
# This line should be self-explanatory

e = np.linspace(1, 10, 10, True, True)
print(e)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


## Dimensionality of arrays

### Zero dimensional arrays or scalars

What we encountered in the above examples are all 'one dimensional arrays', also known as 'vectors'. 'Scalars' are zero-dimensional arrays, with a maximum of one element in it. 

Все, с чем мы столкнулись в приведенных выше примерах, - это "одномерные массивы", также известные как "векторы". "Скаляры"-это массивы нулевой размерности, в которых содержится максимум один элемент.

In [19]:
# Creating a 'scalar'

a = np.array(50)  # Should have only 1 element, at the maximum!

print("a:", a)

a: 50


In [20]:
# To print the dimension of any array, we use 'np.ndim' method

print("The dimension of array 'a' is", np.ndim(a))

The dimension of array 'a' is 0


In [21]:
# To know the datatype of the array

print("The datatype of array 'a' is", a.dtype)

The datatype of array 'a' is int32


In [22]:
# Combining it all together

scalar_array = np.array("one_element")
print(scalar_array, np.ndim(scalar_array), scalar_array.dtype)

one_element 0 <U11


## One-dimensional arrays

One dimensional arrays, are arrays with minimum of two elements in it in a single row.

Одномерные массивы-это массивы с минимум двумя элементами в нем в одной строке.

In [23]:
one_d_array = np.array(["one_element", "second_element"])

print(one_d_array, np.ndim(one_d_array), one_d_array.dtype)

['one_element' 'second_element'] 1 <U14


In [24]:
# We have already worked with one-dimensional arrays. Let us revise what we did so far!

a = np.array([1, 1, 2, 3, 5, 8, 13, 21])  # Fibonnacci series
b = np.array([4.4, 6.6, 8.8, 10.1, 12.12])

print("a: ", a)
print("b: ", b)

print("Type of 'a': ", a.dtype)
print("Type of 'b': ", b.dtype)

print("Dimension of 'a':", np.ndim(a))
print("Dimension of 'b':", np.ndim(b))

a:  [ 1  1  2  3  5  8 13 21]
b:  [ 4.4   6.6   8.8  10.1  12.12]
Type of 'a':  int32
Type of 'b':  float64
Dimension of 'a': 1
Dimension of 'b': 1


## Two-dimensional arrays

Two-dimensional arrays have more than one row and more than one column.

Двумерные массивы имеют более одной строки и более одного столбца.

In [25]:
# The elements of the 2D arrays are stored as 'rows' and 'columns'
two_d_array = np.array([["row1col1", "row1col2", "row1col3"],
                        ["row2col1", "row2col2", "row2col3"]])

print(two_d_array)

print("Dimension of 'two_d_array' :", np.ndim(two_d_array))

[['row1col1' 'row1col2' 'row1col3']
 ['row2col1' 'row2col2' 'row2col3']]
Dimension of 'two_d_array' : 2


In [26]:
# Another example of a data table!
# You can see how working with numpy arrays will help us working with dataframes further on!
studentdata = np.array([["Name", "Year", "Marks"],
                        ["Bela", 2014, 78.2],
                        ["Joe", 1987, 59.1],
                        ["Sugar", 1990, 70]])

print(studentdata)

print("Dimension of 'studentdata' :", np.ndim(studentdata))

[['Name' 'Year' 'Marks']
 ['Bela' '2014' '78.2']
 ['Joe' '1987' '59.1']
 ['Sugar' '1990' '70']]
Dimension of 'studentdata' : 2


Even though Year and Marks are not string type data, here by default they are considered as string type data. So we can't perform any mathematical operations on these values. In order to perform any calculations, we need to convert the data into integers or float type data.

That is where dataframe, which we will study in the next section is very useful. It is a powerful 2-d data structure that can convert the data type with ease and help us perform various operations. 

For example:


Несмотря на то, что Год и отметки не являются данными строкового типа, здесь по умолчанию они рассматриваются как данные строкового типа. Поэтому мы не можем выполнять какие-либо математические операции с этими значениями. Чтобы выполнить какие-либо вычисления, нам нужно преобразовать данные в целые числа или данные типа float.

Именно здесь очень полезен фрейм данных, который мы изучим в следующем разделе. Это мощная 2-d структура данных, которая может легко преобразовать тип данных и помочь нам выполнять различные операции.

Например:

In [27]:
# Example when we save this data as a dataframe and not as a numpy array.
import numpy as np
import pandas as pd

studentdata1 = {
    "Name": ["Bela", "Joe", "Sugar"],
    "Year": [2014, 1987, 1990],
    "Marks": [78.2, 59.1, 70]
}

studentdata1_df = pd.DataFrame(studentdata1)
print(studentdata1_df)
print(np.mean(studentdata1_df.Marks))

# Now we are able to find average of Marks of these three students.

    Name  Year  Marks
0   Bela  2014   78.2
1    Joe  1987   59.1
2  Sugar  1990   70.0
69.10000000000001


In [28]:
# The elements of the 2D arrays are stored as 'rows' and 'columns'
a = np.array([[1.8, 2.4, 5.3, 8.2],
              [7.8, 5.1, 9.2, 17.13],
              [6.1, -2.13, -6.3, -9.1]])
print(a)
print("Dimension of 'a' :", np.ndim(a))

# In this array we have 3 rows and 4 columns

[[ 1.8   2.4   5.3   8.2 ]
 [ 7.8   5.1   9.2  17.13]
 [ 6.1  -2.13 -6.3  -9.1 ]]
Dimension of 'a' : 2


In [29]:
# A 3D array is an 'array of arrays'. Have a quick look at it
b = np.array([[[111, 222], [333, 444]],
              [[121, 212], [221, 222]],
              [[555, 560], [565, 570]]])

print(b)
print("Dimension of 'b' :", np.ndim(b))

# In this array, there are three, 2-D arrays

[[[111 222]
  [333 444]]

 [[121 212]
  [221 222]]

 [[555 560]
  [565 570]]]
Dimension of 'b' : 3


## The shape of an array

**What it is:** Ths shape of an array returns the number of rows (axis = 0) and the number of columns (axis = 1)

**Why is it important to understand:** It helps you to understand the number of rows and columns in an array 

**How is it different from Dimensions:** It is not that different from dimensions, just that functions called are different. 


__Форма массива¶__

Что это такое: Форма массива возвращает количество строк (ось = 0) и количество столбцов (ось = 1)

Почему это важно понять: Это помогает вам понять количество строк и столбцов в массиве

Чем он отличается от измерений: Он не так уж отличается от измерений, просто вызываемые функции отличаются.

In [44]:
a = np.array([[11, 22, 33],
              [12, 24, 36],
              [13, 26, 39],
              [14, 28, 42],
              [15, 30, 45],
              [16, 32, 48]])

print(a)

[[11 22 33]
 [12 24 36]
 [13 26 39]
 [14 28 42]
 [15 30 45]
 [16 32 48]]


In [45]:
print(a.shape)

(6, 3)


In [46]:
a.shape = (9, 2)
print(a)

[[11 22]
 [33 12]
 [24 36]
 [13 26]
 [39 14]
 [28 42]
 [15 30]
 [45 16]
 [32 48]]


We will continue from where we left in the previous notebook.

# Notebook Contents

##### <span style="color:green">1. Indexing</span>
##### <span style="color:green">2. Slicing</span>
#####  <span style="color:green">3. Arrays of 1s and 0s</span>
##### <span style="color:green">4. Identity function</span>

## Indexing

We can access the elements of an array using its **index**. The index gives the location of an element of an array. 

- The first index is '0'.
- The second index is '1' and so on.
- The second last index is '-2'.
- The last index is '-1'.

### Indexing in a one-dimensional array

A one-dimensional array is indexed just like a list.


_Одномерный массив индексируется так же, как и список._

In [86]:
import numpy as np

# One dimensional array
A = np.array([10, 21, 32, 43, 54, 65, 76, 87])

# Print the first element of A
print(A[0])

# Remember, in python, counting starts from 0 and not from 1

10


In [48]:
# Print the last element of A
print(A[-1])

87


In [49]:
# Print the third element of A
print(A[2])

32


In [50]:
# Print the second last element
print(A[-2])

76


### Indexing in a two-dimensional array

A 2-Dimensional Array consists of rows and columns, so you need to specify both rows and columns, to locate an element. 

In [51]:
# Create a 2-Dimensional Array
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(A)

# The shape of the array is : 4 rows and 3 columns

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [52]:
# Print the element of Row 1, column 1
print(A[0][0])

1


In [53]:
# Print the element of row 2, column 1
print(A[1][0])

4


In [54]:
# Print the element of row 4, column 3
print(A[3][2])

12


In [55]:
# Another way to print the element of row 3, column 2
print(A[2, 1])

8


In [56]:
### Try on your own

# Can you guess what will be the output of these print statement?
print(A[4, 3])

IndexError: index 4 is out of bounds for axis 0 with size 4

## Slicing 

When you want to select a certain section of an array, then you slice it. It could be a bunch of elements in a one-dimensional array and/or entire rows and columns in a two-dimensional array. 

### Slicing a one-dimensional array

You can slice a one-dimensional array in various ways:
- Print first few elements
- Print last few elements
- Print middle elements
- Print elements after a certain step. 

Syntax: 
####  array_name [start: stop: step]


In [57]:
# Consider a one-dimensional array A
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# By default, the step = 1

# To print the first 4 elements (i.e. indices 0, 1, 2, 3, those before index 4)
print(A[:4])

# To print the elements from the index = 6 till the end
print(A[6:])

# To print the elements starting from index=2 and it will stop BEFORE index=5

print(A[2:5])

# To print all the elements of the array
print(A[:])

[1 2 3 4]
[7 8]
[3 4 5]
[1 2 3 4 5 6 7 8]


In [58]:
# Introducing step = 2

# This will print alternate index elements of the entire array, starting from index = 0
print(A[::2])

[1 3 5 7]


In [59]:
# Can you guess what will be the output of these print statement?
print(A[::3])

[1 4 7]


### Slicing a two-dimensional array

You can slice a two-dimensional array in various ways:
- Print a row or a column
- Print multiple rows or columns
- Print a section of the table for given rows and columns
- Print first and/or last rows and/or columns.
- Print rows and columns after a certain step. 

Syntax: 
####  array_name [row start: row stop: row step], [col start, col stop, col step]

In [61]:
# A two-dimensional Array
A = np.array([
    ["00", "01", "02", "03", "04"],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
    [30, 31, 32, 33, 34],
    [40, 41, 42, 43, 44]
])

print(A)

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']
 ['30' '31' '32' '33' '34']
 ['40' '41' '42' '43' '44']]


In [62]:
# Print a row or a column
print(A[1, ])  # Printing Row 2

['10' '11' '12' '13' '14']


In [63]:
print(A[:, 1])  # Column 2

['01' '11' '21' '31' '41']


In [64]:
# Print multiple rows or columns

print(A[:2, ])  # Rows 1 & 2

print(A[:, 1:3])  # Columns 2 & 3

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]
[['01' '02']
 ['11' '12']
 ['21' '22']
 ['31' '32']
 ['41' '42']]


In [65]:
# Print first or last rows and columns

print(A[:3, ])  # Printing first three rows

print(A[:, 3:])  # Printing 4th column and onwards

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']
 ['20' '21' '22' '23' '24']]
[['03' '04']
 ['13' '14']
 ['23' '24']
 ['33' '34']
 ['43' '44']]


In [66]:
# Print selected rows and columns
print(A[:2, 2])  # Rows 1 & 2 for column3

['02' '12']


In [67]:
print(A[:3, 2:])  # 1st three rows for the last three columns

[['02' '03' '04']
 ['12' '13' '14']
 ['22' '23' '24']]


In [68]:
print(A[:, :-2])  # Array without last two columns

[['00' '01' '02']
 ['10' '11' '12']
 ['20' '21' '22']
 ['30' '31' '32']
 ['40' '41' '42']]


In [69]:
print(A[:-3, :])  # Array without last 3 rows

[['00' '01' '02' '03' '04']
 ['10' '11' '12' '13' '14']]


In [70]:
# Let us create a new array using the arange method for this exercise

# Create an array with 5 rows, 10 columns that has values from 0 to 49.
A2 = np.arange(50).reshape(5, 10)

print(A2)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [71]:
# Using step in slicing

print(A2[::2, ])  # Print rows 1, 3, and 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]]


In [72]:
print(A2[:, 1:5:2])  # Print columns 2 & 4

[[ 1  3]
 [11 13]
 [21 23]
 [31 33]
 [41 43]]


In [73]:
print(A2[:, 1:10:2])  # Print columns 2,4, 6, 8, 10

[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]


In [74]:
# This will print an intersection of elements of rows 0, 2, 4 and columns 0, 3, 9, 6

print(A2[::2, ::3])

[[ 0  3  6  9]
 [20 23 26 29]
 [40 43 46 49]]


In [75]:
# Let us print all the rows and columns

print(A2[::, ::])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [102]:
### Try on your own

# If the following line of code is self-explanatory to you, then you have understood the entire concept of 2D slicing

print(A2[0:2:1, 0:5:1])

[[ 0  1  2  3  4]
 [10 11 12 13 14]]


In [77]:
# This should be self explanatory

A = np.arange(12)
B = A.reshape(3, 4)

A[0] = 42
print(B)

[[42  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## Array of ones and zeros

In [78]:
O = np.ones((4, 4))
print(O)

# This is default datatype 'float'

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [80]:
O = np.ones((4, 4), dtype=int)  # Changing data type to integer
print(O)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [81]:
Z = np.zeros((3, 3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [82]:
Z = np.zeros((3, 3), dtype=int)
print(Z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Identity function

An identity array has an equal number of rows and columns. It is a square array so that the diagonal elements are all 'ones'. 

In [84]:
I = np.identity(4)

print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [85]:
I = np.identity(3, dtype=int)

print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [93]:
import numpy as np
my_array = np.arange(50).reshape(5,10) # Creating an array with 5 rows, 10 columns which has values from 1 to 50
print(my_array)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


## Vectorization

Vectorization of code helps us write complex codes in a compact way and execute them faster. 

It allows to **operate** or apply a function on a complex object, like an array, "at once" rather than iterating over the individual elements. NumPy supports vectorization in an efficient way.

# Notebook Contents

##### <span style="color:green">1) 1D or 2D Array operations with a scalar</span>
##### <span style="color:green">2) 2D Array operations with another 2D array</span>
##### <span style="color:green">3) 2D Array operations with a 1D array or vector</span>
#####  <span style="color:green">4) Other operators: Compare & Logical</span>
##### <span style="color:green">5) Just for fun</span>

### Array operations with a scalar

Every element of the array is added/multiplied/operated with the given scalar. We will discuss:
- Addition
- Subtraction
- Multiplication

In [104]:
import numpy as np  # Start the notebook with importing the package

my_list = [1, 2, 3, 4, 5.5, 6.6, 7.123, 8.456]

V = np.array(my_list)  # Creating a 1D array or vector

print(V)

[1.    2.    3.    4.    5.5   6.6   7.123 8.456]


#### Vectorization using scalars - addition

In [105]:
V_a = V + 2 # Every element is increased by 2.

print(V_a)

[ 3.     4.     5.     6.     7.5    8.6    9.123 10.456]


#### Vectorization using scalars - subtraction

In [106]:
V_s = V - 2.4  # Every element is reduced by 2.4.

print(V_s)

[-1.4   -0.4    0.6    1.6    3.1    4.2    4.723  6.056]


#### Vectorization using scalars - multiplication

In [108]:
V2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Array of shape 3,3

V_m = V2 * 10  # Every element is multiplied by 10.

print(V2)
print(V_m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


#### Try on your own

In [109]:
V_e = V2 ** 2  # See the output and suggest what this operation is?

print(V_e)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### 2D Array operations with another 2D array

This is only possible when the shape of the two arrays is same. For example, a (2,2) array can be operated with another (2,2) array.

In [110]:
A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])  # Array of shape 3,3
B = np.ones((3, 3))  # Array of shape 3,3
C = np.ones((4, 4))  # Array of shape 4,4
print(A)
print(B)
print(C)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [111]:
# Addition of 2 arrays of same dimensions (3, 3)

print("Adding the arrays is element wise: ")

print(A + B)

Adding the arrays is element wise: 
[[  2.   3.   4.]
 [ 12.  23.  34.]
 [112. 223. 334.]]


In [112]:
# Addition of 2 arrays of different shapes or dimensions is NOT allowed

print("Addition of 2 arrays of different shapes or dimensions will throw a ValueError.")

print(A + C)

Addition of 2 arrays of different shapes or dimensions will throw a ValueError.


ValueError: operands could not be broadcast together with shapes (3,3) (4,4) 

In [113]:
# Subtraction of 2 arrays

print("Subtracting array B from A is element wise: ")

print(A - B)

Subtracting array B from A is element wise: 
[[  0.   1.   2.]
 [ 10.  21.  32.]
 [110. 221. 332.]]


In [114]:
# Multiplication of 2 arrays

A1 = np.array([[1, 2, 3], [4, 5, 6]])  # Array of shape 2,3
A2 = np.array([[1, 0, -1], [0, 1, -1]])  # Array of shape 2,3

print("Array 1", A1)
print("Array 2", A2)
print("Multiplying two arrays: ", A1 * A2)
print("As you can see above, the multiplication happens element by element.")

Array 1 [[1 2 3]
 [4 5 6]]
Array 2 [[ 1  0 -1]
 [ 0  1 -1]]
Multiplying two arrays:  [[ 1  0 -3]
 [ 0  5 -6]]
As you can see above, the multiplication happens element by element.


### Broadcasting allows 2D Array operations with a 1D array or vector

NumPy also supports broadcasting. Broadcasting allows us to combine objects of <b>different shapes</b> within a single operation.

But, do remember that to perform this operation one of the matrices needs to be a vector with its length equal to one of the dimensions of the other matrix.

#### Try changing the shape of B and observe the results

In [115]:
import numpy as np

A = np.array([[1, 2, 3], [11, 22, 33], [111, 222, 333]])
B = np.array([1, 2, 3])

print(A)
print(B)

[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
[1 2 3]


In [116]:
print("Multiplication with broadcasting: ")

print(A * B)

Multiplication with broadcasting: 
[[  1   4   9]
 [ 11  44  99]
 [111 444 999]]


In [117]:
print("... and now addition with broadcasting: ")

print(A + B)

... and now addition with broadcasting: 
[[  2   4   6]
 [ 12  24  36]
 [112 224 336]]


In [118]:
# Try to understand the difference between the two 'B' arrays

B = np.array([[1, 2, 3] * 3])

print(B)

[[1 2 3 1 2 3 1 2 3]]


In [119]:
B = np.array([[1, 2, 3], ] * 3)

print(B)

# Hint: look at the brackets

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [120]:
# Another example type

B = np.array([1, 2, 3])
B[:, np.newaxis]

# We have changed a row vector into a column vector

array([[1],
       [2],
       [3]])

In [121]:
# Broadcasting in a different way (by changing the vector shape)

A * B[:, np.newaxis]

array([[  1,   2,   3],
       [ 22,  44,  66],
       [333, 666, 999]])

In [122]:
# This example should be self explanatory by now

A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
A[:, np.newaxis]

array([[10],
       [20],
       [30]])

In [123]:
A[:, np.newaxis] * B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

### Other operations

- Comparison operators: Comparing arrays and the elements of two similar shaped arrays
- Logical operators: AND/OR operands

In [124]:
import numpy as np

A = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
B = np.array([[11, 102, 13], [201, 22, 203], [31, 32, 303]])

print(A)
print(B)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 11 102  13]
 [201  22 203]
 [ 31  32 303]]


In [125]:
# It will compare all the elements of the array with each other

A == B

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [126]:
# Will return 'True' only if each and every element is same in both the arrays

print(np.array_equal(A, B))

print(np.array_equal(A, A))

False
True


In [127]:
# This should be self explanatory by now

a = np.array([[True, True], [False, False]])
b = np.array([[True, False], [True, False]])

print(np.logical_or(a, b))

[[ True  True]
 [ True False]]


In [128]:
print(np.logical_and(a, b))

[[ True False]
 [False False]]


In [129]:
B = np.array([1, 2, 3])

In [130]:
B

array([1, 2, 3])